# Docker-Compose file.
version: "2"

services:
    web:
        # Serves a static React app from motif-studio/.
        build:
            context: ./motif-studio
            dockerfile: Dockerfile
        ports:
            - "80:80"
        links:
            - motifstudio

    motifstudio:
        # Run a Flask-based web server on port 5000, only visible to web.
        build:
            context: ./server
            dockerfile: Dockerfile.simple
        ports:
            - "5000:5000"
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#     links:
#       - redis
#     command: python app.py
#
#   redis:
#     image: redis
#     ports:
#       - "6379"
#
